name: Build Android Staging Release
# This workflow is triggered on pushes to the repository.
# see https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'

jobs:
  build:
    # Job name is Greeting
    name: Build Android Staging Release
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: echo tag name
        run: echo ${GITHUB_REF/refs\/tags\//}
      -name: notify other project
        run: |
          curl -X POST https://api.github.com/repos/oth-libs/Craftnote-challenge/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u "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" \
          --data '{"event_type": "run-automated-tests", "client_payload": { "apklink": "some link" }}'